// Atoms
export { BzmButtonComponent } from './lib/atoms/button/button.component';
export type { ButtonVariant, ButtonSize } from './lib/atoms/button/button.component';
export { BzmChipComponent } from './lib/atoms/chip/chip.component';
export { BzmAvatarComponent } from './lib/atoms/avatar/avatar.component';
export type { AvatarSize } from './lib/atoms/avatar/avatar.component';
export { BzmBadgeIconComponent } from './lib/atoms/badge-icon/badge-icon.component';
export { BzmNotificationBellComponent } from './lib/atoms/notification-bell/notification-bell.component';
export { BzmSliderComponent } from './lib/atoms/slider/slider.component';
export { BzmCardComponent } from './lib/atoms/card/card.component';
export type { CardVariant } from './lib/atoms/card/card.component';
export { BzmInputComponent } from './lib/atoms/input/input.component';
export type { InputSize } from './lib/atoms/input/input.component';
export { BzmPinInputComponent } from './lib/atoms/pin-input/pin-input.component';
export { BzmSpinnerComponent } from './lib/atoms/spinner/spinner.component';
export type { SpinnerSize } from './lib/atoms/spinner/spinner.component';
export { BzmErrorMessageComponent } from './lib/atoms/error-message/error-message.component';
export { BzmPageTitleComponent } from './lib/atoms/page-title/page-title.component';
export type { PageTitleSize } from './lib/atoms/page-title/page-title.component';
export { BzmSplatComponent } from './lib/atoms/splat/splat.component';
export type { SplatShape } from './lib/atoms/splat/splat.component';
export { BzmMascotComponent } from './lib/atoms/mascot/mascot.component';
export type { MascotExpression, MascotSize, MascotAnimation } from './lib/atoms/mascot/mascot.component';
export { BzmQrCodeComponent } from './lib/atoms/qr-code/qr-code.component';
export type { QrCodeSize } from './lib/atoms/qr-code/qr-code.component';
export { BzmModeToggleComponent } from './lib/atoms/mode-toggle/mode-toggle.component';
export type { GameMode } from './lib/atoms/mode-toggle/mode-toggle.component';
export { BzmSparkCurrencyComponent } from './lib/atoms/spark-currency/spark-currency.component';
export type { SparkCurrencySize } from './lib/atoms/spark-currency/spark-currency.component';
export { BzmStarRatingComponent } from './lib/atoms/star-rating/star-rating.component';
export type { StarCount, StarRatingSize } from './lib/atoms/star-rating/star-rating.component';
export { BzmDifficultyBadgeComponent } from './lib/atoms/difficulty-badge/difficulty-badge.component';
export type { DifficultyTier, DifficultyBadgeSize } from './lib/atoms/difficulty-badge/difficulty-badge.component';
export { BzmRarityBadgeComponent } from './lib/atoms/rarity-badge/rarity-badge.component';
export type { Rarity } from './lib/atoms/rarity-badge/rarity-badge.component';
/** @deprecated Use Rarity instead */
export type { BrainRarity } from './lib/atoms/rarity-badge/rarity-badge.component';
export { BzmStreakCounterComponent } from './lib/atoms/streak-counter/streak-counter.component';
export type { StreakCounterSize } from './lib/atoms/streak-counter/streak-counter.component';
export { BzmPowerUpCardComponent } from './lib/atoms/power-up-card/power-up-card.component';
export type { PowerUpType } from './lib/atoms/power-up-card/power-up-card.component';
/** @deprecated Use Rarity instead */
export type { PowerUpRarity } from './lib/atoms/power-up-card/power-up-card.component';
export { BzmPowerUpNotificationComponent } from './lib/atoms/power-up-notification/power-up-notification.component';
export type { PowerUpNotificationType } from './lib/atoms/power-up-notification/power-up-notification.component';
export { BzmReactionBubbleComponent } from './lib/atoms/reaction-bubble/reaction-bubble.component';
export type { ReactionBubbleSize } from './lib/atoms/reaction-bubble/reaction-bubble.component';
export { BzmCheerMessageComponent } from './lib/atoms/cheer-message/cheer-message.component';
export type { CheerVariant } from './lib/atoms/cheer-message/cheer-message.component';
export { BzmNumericInputComponent } from './lib/atoms/numeric-input/numeric-input.component';
export type { NumericInputSize } from './lib/atoms/numeric-input/numeric-input.component';
export { BzmVolumeControlComponent } from './lib/atoms/volume-control/volume-control.component';
export { BzmStreakIndicatorComponent } from './lib/atoms/streak-indicator/streak-indicator.component';
export type { StreakIndicatorSize } from './lib/atoms/streak-indicator/streak-indicator.component';
export { BzmRankTierBadgeComponent } from './lib/atoms/rank-tier-badge/rank-tier-badge.component';
export type { RankTier, RankTierBadgeSize } from './lib/atoms/rank-tier-badge/rank-tier-badge.component';
export { BzmAchievementToastComponent } from './lib/atoms/achievement-toast/achievement-toast.component';
export { BzmHeartDisplayComponent } from './lib/atoms/heart-display/heart-display.component';
export type { HeartDisplaySize } from './lib/atoms/heart-display/heart-display.component';

// Molecules
export { BzmAnswerOptionComponent } from './lib/molecules/answer-option/answer-option.component';
export type { AnswerLetter } from './lib/molecules/answer-option/answer-option.component';
export { BzmQuizCardComponent } from './lib/molecules/quiz-card/quiz-card.component';
export { BzmLeaderboardItemComponent } from './lib/molecules/leaderboard-item/leaderboard-item.component';
export { BzmLevelProgressComponent } from './lib/molecules/level-progress/level-progress.component';
export { BzmProgressBarComponent } from './lib/molecules/progress-bar/progress-bar.component';
export { BzmTimerComponent } from './lib/molecules/timer/timer.component';
export type { TimerSize } from './lib/molecules/timer/timer.component';
export { BzmRoomCodeComponent } from './lib/molecules/room-code/room-code.component';
export { BzmPlayerListComponent } from './lib/molecules/player-list/player-list.component';
export type { PlayerListItem } from './lib/molecules/player-list/player-list.component';
export { BzmAnswerGridComponent } from './lib/molecules/answer-grid/answer-grid.component';
export type { AnswerGridItem } from './lib/molecules/answer-grid/answer-grid.component';
export { BzmQuestionHeaderComponent } from './lib/molecules/question-header/question-header.component';
export { BzmAnswerFeedbackComponent } from './lib/molecules/answer-feedback/answer-feedback.component';
export { BzmScoreDisplayComponent } from './lib/molecules/score-display/score-display.component';
export type { ScoreDisplaySize } from './lib/molecules/score-display/score-display.component';
export { BzmWaitingStateComponent } from './lib/molecules/waiting-state/waiting-state.component';
export { BzmActionBarComponent } from './lib/molecules/action-bar/action-bar.component';
export type { ActionBarAlign } from './lib/molecules/action-bar/action-bar.component';
export { BzmPowerUpInventoryComponent } from './lib/molecules/power-up-inventory/power-up-inventory.component';
export type { PowerUpSlot } from './lib/molecules/power-up-inventory/power-up-inventory.component';
export { BzmPowerUpActivationComponent } from './lib/molecules/power-up-activation/power-up-activation.component';
export type { PowerUpActivationData } from './lib/molecules/power-up-activation/power-up-activation.component';
export { BzmHostPowerUpFeedComponent } from './lib/molecules/host-power-up-feed/host-power-up-feed.component';
export type { PowerUpFeedItem } from './lib/molecules/host-power-up-feed/host-power-up-feed.component';
export { BzmReactionPickerComponent } from './lib/molecules/reaction-picker/reaction-picker.component';
export type { ReactionOption } from './lib/molecules/reaction-picker/reaction-picker.component';
export { BzmConfidenceWagerComponent } from './lib/molecules/confidence-wager/confidence-wager.component';
export { BzmSpectatorBarComponent } from './lib/molecules/spectator-bar/spectator-bar.component';
export { BzmSpectatorVoteComponent } from './lib/molecules/spectator-vote/spectator-vote.component';
export type { VoteOption } from './lib/molecules/spectator-vote/spectator-vote.component';
export { BzmCategoryCardComponent } from './lib/molecules/category-card/category-card.component';
export type { StarLevel } from './lib/molecules/category-card/category-card.component';
export { BzmBrainCardComponent } from './lib/molecules/brain-card/brain-card.component';
export { BzmBossModifierComponent } from './lib/molecules/boss-modifier/boss-modifier.component';
export { BzmRoundTargetComponent } from './lib/molecules/round-target/round-target.component';
export type { RoundType } from './lib/molecules/round-target/round-target.component';
export { BzmComboAnnounceComponent } from './lib/molecules/combo-announce/combo-announce.component';
export { BzmLearnMoreComponent } from './lib/molecules/learn-more/learn-more.component';
export { BzmShopItemComponent } from './lib/molecules/shop-item/shop-item.component';
export type { ShopItemType } from './lib/molecules/shop-item/shop-item.component';
export { BzmScoreBreakdownComponent } from './lib/molecules/score-breakdown/score-breakdown.component';
export type { BrainMultiplier } from './lib/molecules/score-breakdown/score-breakdown.component';
export { BzmNumberLineComponent } from './lib/molecules/number-line/number-line.component';
export type { NumberLineGuess } from './lib/molecules/number-line/number-line.component';
export { BzmBluffInputComponent } from './lib/molecules/bluff-input/bluff-input.component';
export { BzmImageQuestionComponent } from './lib/molecules/image-question/image-question.component';
export { BzmPartyProgressComponent } from './lib/molecules/party-progress/party-progress.component';
export type { PartyRound } from './lib/molecules/party-progress/party-progress.component';
export { BzmHostOverlayComponent } from './lib/molecules/host-overlay/host-overlay.component';
export type { OverlayStat, OverlayPosition } from './lib/molecules/host-overlay/host-overlay.component';
export { BzmThemePickerComponent } from './lib/molecules/theme-picker/theme-picker.component';
export type { ThemeOption } from './lib/molecules/theme-picker/theme-picker.component';
export { BzmAchievementCardComponent } from './lib/molecules/achievement-card/achievement-card.component';
export type { AchievementCategory } from './lib/molecules/achievement-card/achievement-card.component';
export { BzmMatchHistoryItemComponent } from './lib/molecules/match-history-item/match-history-item.component';
export { BzmGameModeCardComponent } from './lib/molecules/game-mode-card/game-mode-card.component';
export type { GameModeType } from './lib/molecules/game-mode-card/game-mode-card.component';
export { BzmTeamPickerComponent } from './lib/molecules/team-picker/team-picker.component';
export type { TeamOption } from './lib/molecules/team-picker/team-picker.component';
export { BzmBossHealthBarComponent } from './lib/molecules/boss-health-bar/boss-health-bar.component';
export { BzmBossCharacterComponent } from './lib/molecules/boss-character/boss-character.component';
export type { BossExpression, BossSize } from './lib/molecules/boss-character/boss-character.component';
export { BzmRescueBannerComponent } from './lib/molecules/rescue-banner/rescue-banner.component';
export { BzmComebackBannerComponent } from './lib/molecules/comeback-banner/comeback-banner.component';
export { BzmCategoryVoteComponent } from './lib/molecules/category-vote/category-vote.component';
export type { CategoryVoteOption } from './lib/molecules/category-vote/category-vote.component';

// Organisms
export { BzmProfileHeaderComponent } from './lib/organisms/profile-header/profile-header.component';
export { BzmStreakBannerComponent } from './lib/organisms/streak-banner/streak-banner.component';
export { BzmStatsRowComponent } from './lib/organisms/stats-row/stats-row.component';
export { BzmTabBarComponent } from './lib/organisms/tab-bar/tab-bar.component';
export { BzmRankingListComponent } from './lib/organisms/ranking-list/ranking-list.component';
export { BzmCategoryFilterComponent } from './lib/organisms/category-filter/category-filter.component';
export { BzmFriendRowComponent } from './lib/organisms/friend-row/friend-row.component';
export { BzmQuizListComponent } from './lib/organisms/quiz-list/quiz-list.component';
export { BzmLeaderboardComponent } from './lib/organisms/leaderboard/leaderboard.component';
export type { LeaderboardPlayer } from './lib/organisms/leaderboard/leaderboard.component';
export { BzmWinnerCardComponent } from './lib/organisms/winner-card/winner-card.component';
export { BzmCountdownViewComponent } from './lib/organisms/countdown-view/countdown-view.component';
export { BzmQuestionEditorComponent } from './lib/organisms/question-editor/question-editor.component';
export type { QuestionEditorData } from './lib/organisms/question-editor/question-editor.component';
export { BzmHeroComponent } from './lib/organisms/hero/hero.component';
export { BzmComicBackgroundComponent } from './lib/organisms/comic-background/comic-background.component';
export { BzmBluffRevealComponent } from './lib/organisms/bluff-reveal/bluff-reveal.component';
export type { BluffOption, BluffRevealPhase } from './lib/organisms/bluff-reveal/bluff-reveal.component';
export { BzmRoundIntermissionComponent } from './lib/organisms/round-intermission/round-intermission.component';
export type { IntermissionPlayer } from './lib/organisms/round-intermission/round-intermission.component';
export { BzmPauseScreenComponent } from './lib/organisms/pause-screen/pause-screen.component';
export { BzmCategoryHandComponent } from './lib/organisms/category-hand/category-hand.component';
export type { CategoryCardData } from './lib/organisms/category-hand/category-hand.component';
export { BzmBrainSlotBarComponent } from './lib/organisms/brain-slot-bar/brain-slot-bar.component';
export type { EquippedBrain } from './lib/organisms/brain-slot-bar/brain-slot-bar.component';
export { BzmShopViewComponent } from './lib/organisms/shop-view/shop-view.component';
export type { ShopSlot } from './lib/organisms/shop-view/shop-view.component';
export { BzmBossRewardPickerComponent } from './lib/organisms/boss-reward-picker/boss-reward-picker.component';
export type { BossReward } from './lib/organisms/boss-reward-picker/boss-reward-picker.component';
export { BzmRunSummaryComponent } from './lib/organisms/run-summary/run-summary.component';
export type { RunStats } from './lib/organisms/run-summary/run-summary.component';
export { BzmRoundSummaryComponent } from './lib/organisms/round-summary/round-summary.component';
export type { QuestionResult } from './lib/organisms/round-summary/round-summary.component';
export { BzmAgeBandSelectorComponent } from './lib/organisms/age-band-selector/age-band-selector.component';
export type { AgeBand } from './lib/organisms/age-band-selector/age-band-selector.component';
export { BzmAvatarBuilderComponent } from './lib/organisms/avatar-builder/avatar-builder.component';
export type { AvatarConfig } from './lib/organisms/avatar-builder/avatar-builder.component';
export { BzmMatchHistoryComponent } from './lib/organisms/match-history/match-history.component';
export type { MatchHistoryEntry } from './lib/organisms/match-history/match-history.component';
export { BzmPlayerProfileComponent } from './lib/organisms/player-profile/player-profile.component';
export type { PlayerStats } from './lib/organisms/player-profile/player-profile.component';
export { BzmGameModeSelectorComponent } from './lib/organisms/game-mode-selector/game-mode-selector.component';
export type { GameModeOption } from './lib/organisms/game-mode-selector/game-mode-selector.component';
export { BzmTeamScoreboardComponent } from './lib/organisms/team-scoreboard/team-scoreboard.component';
export type { TeamScore } from './lib/organisms/team-scoreboard/team-scoreboard.component';
export { BzmCategoryWheelComponent } from './lib/organisms/category-wheel/category-wheel.component';
export type { CategoryWheelOption } from './lib/organisms/category-wheel/category-wheel.component';
